In [1]:
# Accessing/Changing specific elements, rows, columns

import numpy as np

a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [8]:
# Get a specific element [r, c]
print(a[:, 6])

[ 7 14]


In [10]:
# More fancy [ startindex:endindex: stepsize]

a[0, 1:-1:2]

array([2, 4, 6])

In [11]:
# Changing element

a[1, 3] = 22
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 22 12 13 14]]


In [29]:
# 3D example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b[:, 1, 0])

[3 7]


In [33]:
# replace

b[:,0,0] = [5, 1]
print(b)

[[[5 2]
  [3 4]]

 [[1 6]
  [7 8]]]
