In [2]:
# Initializing Different Types of Arrays
import numpy as np
# All 0s matrix
np.zeros([2,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [3]:
#All 1s matrix
np.ones((4,2,2), dtype="int16")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [4]:
#Any other number (matrix, number)
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [7]:
# full-like
a = ([1,1,1,1,1], [1,1,1,1,1])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [8]:
# random decimal numbers
np.random.rand(4,2,3)

array([[0.57165237, 0.28536528],
       [0.09144382, 0.97381902],
       [0.67491103, 0.35297268],
       [0.09795565, 0.77957918]])

In [10]:
# random integer values
np.random.randint(2,7, size=(3,3))

array([[3, 4, 3],
       [4, 2, 4],
       [4, 5, 6]])

In [11]:
#Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# repeating

arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
