In [10]:
import numpy as np

# The basics

# Initialising Array
a = np.array([1,2,3], dtype = "int16")
print(a)

[1 2 3]


In [4]:
# Two dimentional array
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
# Get Dimention
a.ndim

1

In [6]:
# Get Shape
b.shape

(2, 3)

In [11]:
#Get Type
a.dtype

dtype('int16')

In [12]:
# Get Size
a.itemsize

2

In [15]:
# Get total size
a.size * a.itemsize
a.nbytes

6